stages:
  - commit-phase
  - report-phase
  - uat-phase
  - pat-phase
  - sat-phase
  - deploy-phase

lintFrontend:
  stage: commit-phase
  tags:
    - npm
  script:
    - cd frontend/myCargonaut
    - npm install
    - npm run lint

lintBackend:
  stage: commit-phase
  tags:
    - npm
  script:
    - cd backend
    - npm install
    - npx eslint .

testFrontend:
  stage: commit-phase
  tags:
    - KMS
  image: node-chrome:latest
  before_script:
    - export CHROME_BIN=/usr/bin/google-chrome
    - npm ci
  script:
    - npm run build
    - npm run test --no-watch --no-progress --browsers=ChromeHeadless



testBackend:
  stage: commit-phase
  tags:
    - npm
  script:
    - cd backend
    - npm i
    - npm run test
  allow_failure: false

static_code_analysis:
  stage: report-phase
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  tags:
    - KMS
  script:
    - echo 'Running static code analysis...'
    - sonar-scanner
      -Dsonar.host.url=https://scm.thm.de/sonar
      -Dsonar.projectKey=$SONARCUBE_KEY
      -Dsonar.login=$SONARQUBE_TOKEN