version: '3'
services:
    backend:
        container_name: backend
        build:
            context: backend
            dockerfile: Dockerfile
        env_file:
            - environment.env
        depends_on:
            - database
        restart: unless-stopped
        ports:
            - "3000:3000"

    database:
        container_name: database
        build:
            context: .
            dockerfile: database/Dockerfile
        env_file:
            - environment.env
        restart: always
        hostname: database
        ports:
            - "3306:3306"
            
    frontend:
        container_name: frontend
        build:
            context: frontend/mycargonaut
            dockerfile: Dockerfile
        env_file:
            - environment.env
        depends_on:
            - backend
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
