name: Backend Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd backend
        npm install
    
    - name: RunDatabaseService
      run: |
        docker compose up database -d
        docker compose ps

    - name: Run tests
      run: |
        cd backend
        npm run test
